completed css-three-column-layout
m-Cho1/c0322-code-solutions pull request #19
Opened 2022-03-18 05:53 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/158945488-2dcfdd60-b84b-4673-9cdc-8fc0dd268630.png)

2022-03-18 18:22 UTC, codingcodymiller requested changes

2022-03-18 18:22 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  justify-content: center;
The only styling that should be on a `column` class is `width` or `flex-basis`. Make sure the measurement accurately matches the name of the class as well 🤓 . If you need any other additional styling on top of `width` or `flex-basis`, you should make a separate class that you can add to the element in addition to the `column` class.

2022-03-18 18:22 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  align-items: center;
The only styling that should be on a `column` class is `width` or `flex-basis`. Make sure the measurement accurately matches the name of the class as well 🤓 . If you need any other additional styling on top of `width` or `flex-basis`, you should make a separate class that you can add to the element in addition to the `column` class.

2022-03-21 02:49 UTC, m-Cho1 commented
![image](https://user-images.githubusercontent.com/96744088/159199151-b26af182-79fe-4f4a-9bd5-d1fb66303f95.png)

2022-03-27 23:22 UTC, m-Cho1 commented
edited 3/27/2022

2022-03-28 17:05 UTC, codingcodymiller requested changes

2022-03-28 17:05 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +.flex-basis-column {
How about `column-half`?

2022-03-28 20:16 UTC, m-Cho1 commented
edited! :D

2022-03-29 18:05 UTC, codingcodymiller approved these changes
Nice work!!

2022-03-30 02:22 UTC, merged