Completed css-two-column-layout
m-Cho1/c0322-code-solutions pull request #21
Opened 2022-03-19 16:02 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/159128636-40f5ce68-37e7-4fdf-8eb8-4d9af61cb4c1.png)

2022-03-21 17:40 UTC, codingcodymiller requested changes

2022-03-21 17:40 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
`column` classes should only have `width` or `flex-basis`. You can still use this styling, but you should apply it with a class in addition to a properly structured `column` class. Since this is `column-full`, it should be `width: 100%`

2022-03-21 17:40 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column-halves {
I would renamed this `column-half`

2022-03-21 17:40 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  align-items: baseline;
Again, make this a separate class you can add to the element in addition to the `column-one-third` class.

2022-03-21 17:40 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  padding-top: 15px;
Make this a separate class as well

2022-03-21 17:40 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
`77%` for `halves`? That's not accurate, you should rename this class.

2022-03-21 22:07 UTC, codingcodymiller requested changes
Hey Minji, some of my previous notes still haven't been addressed.

2022-03-21 22:08 UTC, m-Cho1 commented
sorry, I didn't finish the work. I just commit my progress. will be updated shortly!

2022-03-22 02:50 UTC, m-Cho1 commented
![image](https://user-images.githubusercontent.com/96744088/159398098-7a9967ab-6378-485e-9554-0411ae16afbb.png)

I think I'm FINALLY GETTING the utility class!!!

2022-03-22 17:35 UTC, codingcodymiller requested changes

2022-03-22 17:35 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
This should be your `row` class, this is the styling meant to be applied to the `row` class.

2022-03-22 23:32 UTC, m-Cho1 commented
![image](https://user-images.githubusercontent.com/96744088/159593141-74834dd3-d51a-4064-83aa-7ccb97e366e9.png)

2022-03-23 19:55 UTC, codingcodymiller approved these changes
Nice work!

2022-03-24 02:23 UTC, merged