progress-css-canvas-medical
m-Cho1/c0322-code-solutions pull request #22
Opened 2022-03-21 02:20 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/159197512-d8767393-69c4-49a9-b912-b69a459b24b3.png)
![image](https://user-images.githubusercontent.com/96744088/159197546-f01f6898-6401-4831-95ce-af41a59bb7f3.png)
![image](https://user-images.githubusercontent.com/96744088/159197561-fb470c4f-f843-4916-b1ca-7c12674fd3e5.png)

2022-03-21 21:53 UTC, codingcodymiller requested changes
Hey Minji! You seem to be missing a lot of code here, make sure you've pushed all commits you made. If you committed after you pushed the branch, you will need to push it again to send up any code you've committed since then.

2022-03-21 22:20 UTC, codingcodymiller requested changes

2022-03-21 22:20 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      </div>
All your `column` classes in this section are named after the element that you are applying them to, not their size. `column` classes are always meant to be utility classes, which means they are named after what they do. That keeps them reusable in other places. Please revise these and any other `column` classes that are named as if they are semantic classes to be named as utility classes.

2022-03-21 22:20 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-halves list">
You should name this class `column-half` rather than `column-halves`.

2022-03-21 22:20 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
You have quite a few classes here that are just numbering sections, and those class names do not give any hint to their purpose. Creating good names for things is **_extremely_** important in CSS. If it's a utility class, it should mention what it does. If it's a semantic class, it should describe what it is being applied to. Please review all class names you've created, and make sure they are named effectively based on their purpose.

2022-03-27 22:50 UTC, m-Cho1 commented
edited on 3/27/2022

2022-03-28 17:28 UTC, codingcodymiller approved these changes
Great work! 👏

2022-03-28 19:59 UTC, merged