Completed css-four-column-layout
m-Cho1/c0322-code-solutions pull request #27
Opened 2022-03-22 04:59 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/159411194-33fc1b87-11ce-4a36-9570-fb2792a51c83.png)

2022-03-22 18:25 UTC, codingcodymiller requested changes

2022-03-22 18:25 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +}
This should be the `row` class

2022-03-22 21:53 UTC, m-Cho1 commented
![image](https://user-images.githubusercontent.com/96744088/159582511-fc93a3e8-9271-4aba-86dc-1e392c828c2e.png)

2022-03-24 18:55 UTC, codingcodymiller approved these changes

2022-03-24 21:35 UTC, merged