Javascript data model
m-Cho1/c0322-code-solutions pull request #28
Opened 2022-03-22 20:03 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/159559974-fff358ea-1d81-42f8-bc45-67dc21dc45e0.png)

2022-03-23 19:44 UTC, codingcodymiller requested changes

2022-03-23 19:44 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +      }
This one object contains the data for both items, that is misleading. You should have one object for each item in this array

2022-03-24 04:45 UTC, m-Cho1 commented
Edited!

2022-03-24 18:47 UTC, codingcodymiller approved these changes

2022-03-24 19:32 UTC, codingcodymiller approved these changes

2022-03-24 19:33 UTC, codingcodymiller approved these changes

2022-03-24 21:35 UTC, merged