Completed javascript-light-bulb
m-Cho1/c0322-code-solutions pull request #45
Opened 2022-03-29 20:28 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/160701161-c0d66f12-8f75-47b4-baa2-fd06a830cd99.png)
![image](https://user-images.githubusercontent.com/96744088/160701186-7473469b-539f-4d26-b12c-371a5d1facd7.png)

2022-03-29 21:52 UTC, codingcodymiller requested changes

2022-03-29 21:52 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  clicks++;
Rather than using a counter variable then checking if the value is even or odd, I would suggest using a boolean to keep track of if the light is currently on or off, and re-assign the value to the opposite boolean every time the user clicks the light switch.

2022-03-29 22:19 UTC, m-Cho1 commented
Edited!

2022-03-30 17:55 UTC, codingcodymiller approved these changes
Nice work!!

2022-03-30 21:21 UTC, merged