Completed javascript-modal
m-Cho1/c0322-code-solutions pull request #46
Opened 2022-03-30 00:34 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/160727945-c0f7d288-7976-4feb-9910-4389df61bd21.png)
![image](https://user-images.githubusercontent.com/96744088/160727960-355143d6-dcfb-4fca-a8a8-41c89a222fbc.png)

2022-03-30 18:09 UTC, codingcodymiller requested changes

2022-03-30 18:09 UTC, codingcodymiller commented on javascript-modal/styles.css
> +  align-items: center;
I bet if you apply these properties to `.popup-container`, you can avoid using `absolute` positioning here.

2022-03-30 18:09 UTC, codingcodymiller commented on javascript-modal/styles.css
> +  height: 100%;
Percentage does not work on height without an ancestor element with a set size. Web applications are meant to be able to scroll infinitely, so the viewport does not actually have a height in the browser that you can use a percentage on. If you want an element to take up the full height of the viewport, you should use `100vh`

2022-03-30 20:45 UTC, m-Cho1 commented on javascript-modal/styles.css
> +  align-items: center;
I still had to use them for the text and button. when I apply them to .popup-container and remove absolute position in the .popup-message, the next and button located top of the box instead of middle.

2022-03-30 21:40 UTC, codingcodymiller requested changes

2022-03-30 21:40 UTC, codingcodymiller commented on javascript-modal/styles.css
> +  align-items: center;
Even with that being the case, you should still revise this. Since the message is a child of the background behind the modal, you should only need `fixed` position on the `popup-container` class, and no positioning should be necessary to position the message or the content inside the message, those can all be controlled with normal document flow and flexbox.

2022-03-31 03:06 UTC, m-Cho1 commented
Edited, thank you for the feedback Cody!!

2022-03-31 16:18 UTC, codingcodymiller requested changes

2022-03-31 16:18 UTC, codingcodymiller commented on javascript-modal/styles.css
> +  top: 163px;
What happens if you remove these properties?

2022-04-01 16:04 UTC, codingcodymiller approved these changes
Nice work!

2022-04-01 20:07 UTC, merged