Completed html-forms
m-Cho1/c0322-code-solutions pull request #7
Opened 2022-03-15 23:25 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/158488353-7773ec34-9e61-4d85-bf8a-e32772e47f2c.png)

2022-03-15 23:41 UTC, codingcodymiller requested changes

2022-03-15 23:41 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="checkbox" name="sign-me-up" checked="" /> Sign me up!
The text "Sign me up!" should be in a `label` element here

2022-03-15 23:41 UTC, codingcodymiller commented on html-forms/index.html
> +        </label>
This text doesn't correlate to one specific form control element, so it can just be a general text element such as `p`

2022-03-15 23:41 UTC, codingcodymiller commented on html-forms/index.html
> +        </label>
This `label`'s `for` attribute does not match the `id` attribute on the form control element it is paired with.

2022-03-15 23:41 UTC, codingcodymiller commented on html-forms/index.html
> +          <input id="email" type="text" name="email" /></label><br />
You should move the closing tag for the `label` element to its own line, since the opening tag was on its own line

2022-03-16 00:07 UTC, m-Cho1 commented
Edited!
![image](https://user-images.githubusercontent.com/96744088/158491542-693216f8-1a52-4d1f-a763-1fbeac724fd9.png)

2022-03-16 00:26 UTC, codingcodymiller requested changes

2022-03-16 00:26 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="checkbox" name="sign-me-up" checked="" />
This `input` needs an `id` to match the `for` on its matching `label`

2022-03-16 00:29 UTC, m-Cho1 commented
Edited-2
![image](https://user-images.githubusercontent.com/96744088/158493739-0ca92dee-6c9b-4c5d-8985-8b3b0c18b63d.png)

2022-03-16 00:33 UTC, codingcodymiller approved these changes

2022-03-16 00:58 UTC, merged